spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/max"
    username: "max"
    password: "1111"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
        format_sql: false
        globally_quoted_identifiers: true
#  security:
#    user:
#      password: 1111